### ISSUE TITLE
Duplicated Py scripts?

### ISSUE THREAD

**Issue by simoneSantoni** [simoneSantoni/digital-leadership-center#6]
I don't understand what's the difference between:

```digital-leadership-center/dataViz/dynamicViz/main.py```

and 

```digital-leadership-center/dataViz/dynamicViz/Visualistion/index_viz_clean/main.py```

**Comment by averysoh** [comment]
Apologies might have uploaded it twice in different locations, there should be only one main.py script and that has to do with launching the visualisation
